<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxkIOP1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxkIOP1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxkIOP1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxkIOP1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxkIOP1\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxkIOP1',
    'container.build_id' => '313ce071',
    'container.build_time' => 1597860748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxkIOP1');
